spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      first:  #数据源1,董翔祥的阿里云MariaDB数据库
        username: dxx
        url: jdbc:mysql://120.79.254.175:3306/sdses_security?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
        password: dxx19971221
      #second:  #数据源2
        #url: jdbc:mysql://120.79.254.175:3306/sdses_security?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        #username: root
        #password: root
      initial-size: 20
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

  #热部署生效
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
      exclude: statics/**,templates/**

  #微信配置
  wechat:
    JsSDK:
      appId: wx679677b804f19fcc
      appSecret: 73b6c99b7556e5a590347f6b6e8a7945
    access_token_url_model: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
    jsapi_ticket_url_model: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=ACCESS_TOKEN&type=jsapi





file:
    #静态资源访问路径
    staticAccessPath: /uploadFile/**
    #文件上传目录
    uploadFolder: file:D:/uploadFile/
    uploadPath: D://uploadFile/
    tempFilePath: D://uploadFile/temp/